### ISSUE TITLE
how to continue?

### ISSUE THREAD

**Issue by guaka** [guaka/hitchticker#6]
I'm happy to work on this but it's not clear what's expected. Please add some screenshots or links to stuff that this is supposed to look like.

**Comment by UserStefan** [comment]
Sorry, used the ticker already some days ago for this. We continue here.

i like the style. messages are divided by a simple line. you have the date/time and the headline can be taken by the username. if the design is responsible in addition it is perfect i guess. 23 days ago mettamensch@gmail.com
http://rb-fans.de/liveticker.html 23 days ago mettamensch@gmail.com
also the date and time of the post would be nice instead of "[time] ago", more like 05.02.2015: 15:18 a month ago mettamensch@gmail.com

**Comment by guaka** [comment]
continuing nicely with @simison now, who's sitting next to me
